name: GitHub Actions CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install gems
      run: |
        gem install -N bundler
        bundle install --jobs 4 --retry 3
        gem cleanup
    - name: Test Ruby
      run: bundle exec rake rubocop
